### ISSUE TITLE
Soft Lock game. Fall infinitely out of bounds

### ISSUE THREAD

**Issue by thatstoofar** [taurheim/Fungi#36] opened 2018-01-03 21:06 UTC
![image](https://user-images.githubusercontent.com/14252147/34539780-fdef573c-f09f-11e7-84ed-d447be350a95.png)

**Comment by JosephAQM** [comment] 2018-01-04 05:10
Duplicate of issue #14

**Closed as completed** 2018-01-16 20:25 UTC
Labels: duplicate
