### ISSUE TITLE
Visual Bugs 

### ISSUE THREAD

**Issue by thatstoofar** [taurheim/Fungi#42] opened 2018-01-03 21:20 UTC
![image](https://user-images.githubusercontent.com/14252147/34540280-f27368ce-f0a1-11e7-9b95-ded4a4c89e4d.png)
![image](https://user-images.githubusercontent.com/14252147/34540301-03e8ce14-f0a2-11e7-82cf-a30acb7648e8.png)

**Comment by taurheim** [comment] 2018-01-16 20:35
Duplicate of #22

**Closed as completed** 2018-01-24 14:45 UTC
Labels: duplicate
