### ISSUE TITLE
Give walking animation to the alien in level 2. Right now he glides on the floor and it seems really weird.

### ISSUE THREAD

**Issue by zahids4** [taurheim/Fungi#114] opened 2018-01-11 04:25 UTC
<img width="912" alt="screen shot 2018-01-10 at 11 24 11 pm" src="https://user-images.githubusercontent.com/11669872/34808532-8034bf08-f65d-11e7-81d7-c5dad45dd6d0.png">

**Comment by taurheim** [comment] 2018-01-16 21:18
Duplicate of #58

**Closed as completed by taurheim** 2018-01-16 21:18 UTC
Labels: duplicate
