### ISSUE TITLE
AI gets bunched up

### ISSUE THREAD

**Issue by puruj** [taurheim/Fungi#23] opened 2018-01-03 07:01 UTC
I went through one of the doors and saw all the AI bunched up.
![image](https://user-images.githubusercontent.com/6410204/34511483-f25d7ec4-f029-11e7-84c6-30b1d7ead21d.png)

**Comment by JosephAQM** [comment] 2018-01-04 05:11
Duplicate of issue #10

**Closed as completed** 2018-01-16 20:19 UTC
Labels: duplicate
