### ISSUE TITLE
You can see the node radar from alien's point of view

### ISSUE THREAD

**Issue by thatstoofar** [taurheim/Fungi#38] opened 2018-01-03 21:13 UTC
![image](https://user-images.githubusercontent.com/14252147/34540033-04fb2168-f0a1-11e7-846c-36386f375097.png)

**Comment by taurheim** [comment] 2018-01-16 20:27
Duplicate of #17, props for figuring out what it was though :D

**Closed as completed by taurheim** 2018-01-16 20:27 UTC
Labels: duplicate
