### ISSUE TITLE
I can clip out of bounds and get out of the map

### ISSUE THREAD

**Issue by thatstoofar** [taurheim/Fungi#35] opened 2018-01-03 21:03 UTC
![image](https://user-images.githubusercontent.com/14252147/34539746-d7492bf8-f09f-11e7-8e1f-41f53332a9ef.png)

**Comment by thatstoofar** [comment] 2018-01-03 21:05
![image](https://user-images.githubusercontent.com/14252147/34539759-e79b8e7e-f09f-11e7-89dd-d5436ca492b1.png)

**Comment by taurheim** [comment] 2018-01-16 20:24
Duplicate of #11

**Closed as completed by taurheim** 2018-01-16 20:24 UTC
Labels: duplicate
