### ISSUE TITLE
Went outside of the level when jumping with the aliens with hair (Level 1)

### ISSUE THREAD

**Issue by VictoriaGraff** [taurheim/Fungi#84] opened 2018-01-04 18:59 UTC
![fungi](https://user-images.githubusercontent.com/17343121/34579560-7791ed7c-f157-11e7-842e-d369d01b533a.png)

**Comment by taurheim** [comment] 2018-01-16 21:01
Duplicate of #11

**Closed as completed by taurheim** 2018-01-16 21:01 UTC
Labels: duplicate
