### ISSUE TITLE
Visual glitches on wall tiles in Level 1

### ISSUE THREAD

**Issue by junhao-wang** [taurheim/Fungi#57] opened 2018-01-04 05:09 UTC
In the room the player spawns in, there are several wall tiles that to be placed over something else, and the two similar coloured textures are overlapping in weird ways.
![image](https://user-images.githubusercontent.com/15987116/34550976-73673a5a-f0e3-11e7-9232-71511229a2c9.png)

**Comment by taurheim** [comment] 2018-01-16 20:46
Duplicate of #22

**Closed as completed by taurheim** 2018-01-16 20:46 UTC
Labels: duplicate
